BOX_IMAGE = "bento/ubuntu-25.04"
BOX_VERSION = "202510.26.0"

Vagrant.configure("2") do |config|
  config.vm.box = BOX_IMAGE
  config.vm.box_version = BOX_VERSION

  config.vm.define "gh-runner" do |runner|
    runner.vm.hostname = "gh-runner"
    runner.vm.network "private_network", ip: "192.168.56.50"

    runner.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = 4096
    end

    runner.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y curl tar sudo git
      useradd -m -s /bin/bash github
      echo "github ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
    SHELL
  end
end